name: Deploy Terminal Resume

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate build metadata
        run: |
          echo "Creating build.json"

          VERSION="v1.0.$GITHUB_RUN_NUMBER"
          DATE=$(date -u +"%Y-%m-%d %H:%M UTC")
          COMMIT=$(git rev-parse --short HEAD)

          cat <<EOF > build.json
          {
            "version": "$VERSION",
            "lastDeploy": "$DATE",
            "commit": "$COMMIT"
          }
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
