name: Generate and Commit PDF Resume

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Download JSON resume from Gist (optional)
      - name: Download resume JSON
        run: |
          curl -L -o resume.json https://gist.githubusercontent.com/wisamalabed/6c826f000b9d865a34c0ba6a4841cdb1/raw/


      # Step 3: Generate PDFs using Devleaps JSON Resume Generator
      - name: Generate PDF Resume
        uses: Devleaps/jsonresume-generator@v1
        with:
          action: "render"
          file: "resume.json"
          theme-name: "jsonresume-theme-even"
          output-type: "pdf"
          theme-local: "false"
      
      - name: Rename Even PDF
        run: mv resume.pdf resume-even.pdf     

      - name: Generate PDF - Macchiato Theme
        uses: Devleaps/jsonresume-generator@v1
        with:
          action: "render"
          file: "resume.json"
          theme-name: "jsonresume-theme-macchiato"
          output-type: "pdf"
          theme-local: "false"
      
      - name: Rename Macchiato PDF
        run: mv resume.pdf resume-macchiato.pdf


      - name: Generate PDF - Bold Header Theme
        uses: Devleaps/jsonresume-generator@v1
        with:
          action: "render"
          file: "resume.json"
          theme-name: "jsonresume-theme-bold-header-statement"
          output-type: "pdf"
          theme-local: "false"

      - name: Rename Bold Header PDF
        run: mv resume.pdf resume-bold-header.pdf

      - name: Commit PDFs back to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add resume-*.pdf
          git commit -m "Update generated resumes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}